server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: message

  main:
    allow-circular-references: true

## OracleDriver
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:meta-final.cfj95decnpve.ap-northeast-2.rds.amazonaws.com:1521:ORCL
    username: admin
    password: {암호를 입력해주세요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!}

## MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.metanet.metamungmung.dto
